[project]
name = "easiauto"
version = "0.3.0"
description = "自动登录希沃白板的CLI工具"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nuitka>=2.7.16",
    "opencv-python>=4.12.0.88",
    "pillow>=11.3.0",
    "pyautogui>=0.9.54",
    "pyside6>=6.9.3",
    "pywin32>=311",
    "tenacity>=9.1.2",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.ruff]
line-length = 120
