[project]
name = "auto_login_for_easinote"
version = "0.2.0"
description = "自动登录希沃白板的CLI工具"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.2.1",
    "pyautogui>=0.9.54",
    "tenacity>=9.1.2",
    "win11toast>=0.35",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
